import type { DataWindow } from "./markets";

/** MEXC USDT-M perpetual + spot chart windows (UTC). */
export const CASE_STUDY_WINDOWS: Record<string, DataWindow> = {
  "hammer-at-support": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1678377600000,
    limit: 6,
    marketType: "futures",
    highlight: [4, 5],
    label: "Mar 2023 · SVB crisis dip · ~$19.5k support",
  },
  "failed-breakout": {
    symbol: "BTCUSDT",
    interval: "1d",
    startTime: 1684281600000,
    limit: 7,
    marketType: "futures",
    highlight: [5, 6],
    label: "May 2023 · $27.5k resistance bull trap",
  },
  "trend-continuation": {
    symbol: "ETHUSDT",
    interval: "4h",
    startTime: 1701388800000,
    limit: 8,
    marketType: "futures",
    highlight: [3, 4, 5],
    label: "Nov 2023 · ETH perp uptrend pullback",
  },
  "btc-range-bound": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1693540800000,
    limit: 8,
    marketType: "futures",
    highlight: [2, 3, 4],
    label: "Aug 2023 · $25.5k–$26k range chop",
  },
  "btc-liquidation-cascade": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1693569600000,
    limit: 6,
    marketType: "futures",
    highlight: [1, 2, 3],
    label: "Aug 2023 · liquidation wick to $25.3k",
  },
  "eth-confluence-breakout": {
    symbol: "ETHUSDT",
    interval: "1d",
    startTime: 1711929600000,
    limit: 6,
    marketType: "futures",
    highlight: [1, 2, 5],
    label: "Apr 2024 · ETH dip + V-recovery",
  },
  "spot-dca-dip": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1678377600000,
    limit: 6,
    marketType: "spot",
    highlight: [4, 5],
    label: "Mar 2023 · Spot DCA zone ~$19.5k",
  },
  "spot-breakout-accumulation": {
    symbol: "ETHUSDT",
    interval: "1d",
    startTime: 1701388800000,
    limit: 7,
    marketType: "spot",
    highlight: [3, 4, 5, 6],
    label: "Nov 2023 · ETH spot accumulation breakout",
  },
};

export const TUTORIAL_WINDOWS: Record<string, DataWindow> = {
  "bullish-engulfing-btc": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1678449600000,
    limit: 2,
    marketType: "futures",
    highlight: [0, 1],
  },
  "morning-star-btc": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1678420800000,
    limit: 3,
    marketType: "futures",
    highlight: [0, 1, 2],
  },
  "three-soldiers-eth": {
    symbol: "ETHUSDT",
    interval: "4h",
    startTime: 1701388800000,
    limit: 3,
    marketType: "futures",
    highlight: [0, 1, 2],
  },
  "btc-range-window": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1693540800000,
    limit: 5,
    marketType: "futures",
  },
  "btc-range-bound-lesson": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1693540800000,
    limit: 8,
    marketType: "futures",
  },
  "eth-confluence-breakout": {
    symbol: "ETHUSDT",
    interval: "1d",
    startTime: 1711929600000,
    limit: 6,
    marketType: "futures",
  },
  "spot-hammer-btc": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1678435200000,
    limit: 2,
    marketType: "spot",
    highlight: [0, 1],
  },
};

export const LESSON_WINDOWS: Record<string, DataWindow> = {
  "btc-basics-sample": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1678406400000,
    limit: 5,
    marketType: "futures",
  },
  "spot-btc-sample": {
    symbol: "BTCUSDT",
    interval: "4h",
    startTime: 1678406400000,
    limit: 5,
    marketType: "spot",
  },
};
